
application: itranswarp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /(.+)/static/(.*)
  static_files: \1/static/\2
  upload: (.+)/static/(.*)

- url: /install
  script: gaeapp.app
  login: admin

- url: /.*
  script: gaeapp.app

builtins:

- appstats: on

- remote_api: on

libraries:

- name: PIL
  version: "latest"

- name: jinja2
  version: "latest"
